Fix/groups
amplitude/amplitude-browser-sdk-gtm-template pull request #8
Opened 2023-03-23 14:55 UTC by sahava

Previously, the "track" command when tracking with groups simply included the group key-value pairs in the eventOptions object, so it looked like:

`amplitude('track', event_name, event_properties, event_options_including_groups)`

I fixed this so that groups are included in an object with event_name:

`amplitude('track', {event_type: event_name, groups: groups}, event_properties, event_options)`

Seems to work fine, but would be good to have some one take a check before merging with `main`.

2023-03-29 18:31 UTC, yuhao900914 approved these changes
LGTM. Curious do we also need to add groupProperties in the track method?
Usually, the event-level group event might need both groups and groupProperties.

2023-03-30 05:24 UTC, sahava commented
> LGTM. Curious do we also need to add groupProperties in the track method? Usually, the event-level group event might need both groups and groupProperties. But this is another topic, we can merge this first.

Currently `groupIdentify` is its separate command in the template. Does the Amplitude Browser SDK support adding groupProperties in the `track` call, too? That would certainly streamline things. We can discuss over Slack, I'll publish this.

2023-03-31 21:46 UTC, yuhao900914 requested changes
[packages/analytics-types/src/base-event.ts](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/base-event.ts#L9)
Actually based on here. The type of the groups should be `[key: string]: any`.

I think in line 981, the structure of the groups should be 
```
{eventGroupType:xxx, eventGroupName:xxx}
```
Should we change it to 
```
group.eventGroupType: group.eventGroupName && group.eventGroupName.indexOf(',') > -1 ? stringToArrayAndTrim(group.eventGroupName) : group.eventGroupName;
```

2023-04-01 09:17 UTC, sahava commented
> [packages/analytics-types/src/base-event.ts](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/base-event.ts#L9) Actually based on here. The type of the groups should be `[key: string]: any`.
> 
> I think in line 981, the structure of the groups should be
> 
> ```
> {eventGroupType:xxx, eventGroupName:xxx}
> ```
> 
> Should we change it to
> 
> ```
> group.eventGroupType: group.eventGroupName && group.eventGroupName.indexOf(',') > -1 ? stringToArrayAndTrim(group.eventGroupName) : group.eventGroupName;
> ```

The `makeTableMap` API (https://developers.google.com/tag-platform/tag-manager/templates/api#maketablemap) actually does this. The input is [{eventGroupType: xxx, eventGroupName: yyy}, {eventGroupType: aaa, eventGroupName: bbb}], and `makeTableMap` converts it to `{xxx: yyy, aaa: bbb}`.

That's how the groups should be added to the event call, right?

2023-04-03 20:58 UTC, yuhao900914 approved these changes
Good to know. I'm good with the changes!

2023-04-06 05:56 UTC, sahava commented
> Good to know. I'm good with the changes! Thanks, Simo. I just merged some changes to the gtm template. So the metadata.yaml has some conflicts. Please fix that before merging. Or I'm also happy to fix that conflict and merge that for you. Let me know.

Hi!

Feel free to finalize the merge – it's important that `metadata.yaml` be updated with the commit hash of the last update to `template.tpl` similar to how the previous updates were done into the metadata file. So the latest update needs to be the first in the list, and `changeNotes` needs to reflect what was changed.

2023-04-14 17:59 UTC, closed without merging